= Deploying Your Project
:keywords: mozart

Mozart allows you to easily deploy your application straight from the editor, without needing to leave the screen. You can use this as a way to test and debug your application as you develop it, periodically deploying it to check that


== Deploy to CloudHub

Mozart offers a simple shortcut to deploy your application on link:/runtime-manager/cloudhub[CloudHub], without needing to go through the link:/runtime-manager[Runtime Manager console].

Simply click the play button on the top nav bar

image[]

Your application is then deployed to CloudHub, registering it through the same name with which you created the Mozart project. Once deployed it becomes reachable through a URL that follows the structure *appName.cloudhub.io*  (????)

[NOTE]
====
Keep in mind that CloudHub applications are deployed to a specific link:/access-management/environments[environment] (i.e: Dev, QA, Production). If your Anypoint Platform organization handles multiple environments, you select on what environment to deploy your Mozart project when creating it. See link:/design-center/v/1.0/index#create-new[create new].

Make sure you're aware of the consequences of deploying to the selected environment, as by deploying it you might be giving your app more exposure than you want to give it at the time.
====


As the application is deployed, its status is indicated next to it as it changes from *Undeployed* to *Deploying* to *Deployed* or indicates any errors.

image[]

You can also view more details about your deployment by viewing the *Deployment Pannel*, to open it click the corresponding icon:

image[]

In this pannel, you can see..   stuff      as well as the deployment console, where you can get more details about the current state of the deployment as well as specific error messages.

image[]





After deploying, you can go to the Runtime Manager console and see your application there and link:/runtime-manager/managing-deployed-applciations[manage your application] just like any other application deployed through the console.

[NOTE]
The Mozart UI only allows you to deploy projects to run in the environment in which you created the project.


== Deploy To Other Servers

For deploying to customer-managed Mule runtimes (all except CloudHub), you must first export your project to Anypoint Studio, and then export a .zip deployable archive from there.  (link)

image[export icon]
