= Deploying Your Project
:keywords: mozart

Mozart allows you to easily deploy applications straight from the editor, without needing to leave the editing screen. You can use this as a way to test and debug your application as you develop it, periodically deploying it to check that it works as expected. When your application is finished, you can also use this feature to deploy your application to a production environment.


== Deploy to CloudHub

Mozart offers a simple shortcut to deploy your application on link:/runtime-manager/cloudhub[CloudHub], without needing to go through the the link:/runtime-manager[Runtime Manager console].

Simply click the play button on the top nav bar

image[]

Your application is then deployed to CloudHub, registering it by default through the same name with which your Mozart project. Once deployed it becomes reachable through a URL that follows the structure *appName-environment.cloudhub.io*  (????)

You can change this default name by opening <<The Deployment Pannel>>, this also changes the deployment URL.


As the application is deployed, its status is indicated next to it as it changes from *Undeployed* to *Deploying* to *Deployed* or indicates any errors.

image[]

== The Deployment Pannel

You can edit and view more details about your deployment through the *Deployment Pannel*, to open it click the corresponding icon:

image[]

On this pannel you can view the deployment console, which displays details about the current state of the deployment as well as specific error messages.

image[]

You can also change the name of the app on CloudHub, which also changes the address with which your service is exposed


And you can also change the CloudHub link:/access-management/environments[environment] to which to deploy. When selecting a different environment, you can configure the link:/design-center/v/1.0/mozart#global-elements[global elements] in your project so that they have different settings for each of your environments.

image

[NOTE]
====
Keep in mind that CloudHub applications are deployed to a specific link:/access-management/environments[environment] (i.e: Dev, QA, Production).

Make sure you're aware of the consequences of deploying to the selected environment, as by deploying it you might be giving your app more exposure than you want to give it at the time.
====


After deploying, you can go to the Runtime Manager console and link:/runtime-manager/managing-deployed-applciations[manage your application] in the same way as any other.




== Deploy To Other Servers

For deploying to customer-managed Mule runtimes (all except CloudHub), you must first export your project to Anypoint Studio, and then export a .zip deployable archive from there.  (link)

image[export icon]
