= Deploying Your Project
:keywords: mozart, flow designer, deploy, environments

The flow designer allows you to easily deploy applications straight from the editor, without needing to leave the editing screen. You can use this as a way to test and debug your application as you develop it, periodically deploying it to check that it works as expected. When your application is finished, you can also use this feature to deploy your application to a production environment.


== Deploy to CloudHub

The flow designer offers a simple shortcut to deploy your application on link:/runtime-manager/cloudhub[CloudHub], without needing to go through the the link:/runtime-manager[Runtime Manager console].

Simply click the play button on the top nav bar:

image[]

Your application is then deployed to CloudHub. Each application that you develop in Design Center is linked to a CloudHub worker, which is by default registered with the same name with which your Design Center project. Once deployed it becomes reachable through a URL that follows the structure *appName.cloudhub.io*. You can change this default name by opening <<The Deployment Panel>>, this also changes the deployment URL.


As the application is deployed, its status is indicated next to it as it changes from *Undeployed* to *Deploying* to *Deployed* or indicates any errors.

image[]

== The Deployment Panel

You can edit and view more details about your deployment through the *Deployment Panel*, to open it click the corresponding icon:

image[]

On this panel you can view the deployment console, which displays details about the current state of the deployment as well as specific error messages.

image[]

You can also change the name of the app on CloudHub, which also changes the address with which your service is exposed.


== Promoting Applications

Click the *Promote Application* button to deploy it to a production environment.



This displays a window where you can select a name with which to deploy your application and the CloudHub link:/access-management/environments[environment] to which to deploy. When selecting a different environment, you can configure the link:/design-center/v/1.0/flow-designer#global-elements[global elements] in your project so that they have different settings for each of your environments.

image

[NOTE]
====
Keep in mind that CloudHub applications are deployed to a specific link:/access-management/environments[environment] (i.e: Dev, QA, Production).

Make sure you're aware of the consequences of deploying to the selected environment, as by deploying it you might be giving your app more exposure than you want to give it at the time.
====

This creates a copy of your application and passes it to Runtime Manager to deploy.


After deploying, you can go to the Runtime Manager console and link:/runtime-manager/managing-deployed-applciations[manage your application] in the same way as any other.

image:


=== Environment Specific Settings

The application promotion screen also allows you to set variables that may be specific to a given link:/access-management/environments[environment].

The fields exposed here are those that can be set in the link:/design-center/v/1.0/flow-designer#global-configurations[Global Configurations] of each element in your flow.

This allows you to tweak your application with values that may point to equivalent assets that are in different environments, such as a staging database for your staging deployment, and a production database for your production deployments. This eliminates the need to add property placeholders.




////
== Deploy To Other Servers

For deploying to customer-managed Mule runtimes (all except CloudHub), you must first export your project to Anypoint Studio, and then export a .zip deployable archive from there.  (link)
??? still true??   now we have a full fledged app


image[export icon]
////
