= Flow Designer
:keywords: mozart

The flow designer is one of the tools in the link:/design-center[Design Center]. It is a simplified web-based visual design tool that allows you to create and deploy Mule applications very easily. It can be thought of as a subset of link:/anypoint-studio[Anypoint Studio] (the desktop IDE) that is streamlined to require minimum configuration. With a strong focus on usability, the flow designer allows you to get things done with very little effort and without needing to go deep into learning the underlying concepts. It's oriented towards users that, whilst having a general technical background, don't need to understand Java or advanced connectivity concepts.

The flow designer allows you to build upon reusable assets, enabling anyone who needs to put together an integration to compose applications in a self-serve manner. They can combine both out-of-the-box components and those that have been created by integration specialists in your organization.

The flow designer's editor allows you to directly deploy your applications to CloudHub without ever leaving the screen. You might want to periodically deploy your project to a Dev environment while building and debugging, and then – when ready – simply change the deployment target to the Production environment, all without ever leaving the editor.

[TIP]
In future releases, applications built in the flow designer will also be exportable to Anypoint Studio (the desktop IDE) for configuring advanced settings. With that feature, you could have a workflow where the desired overall functionality is drafted by line-of-business users on Design Center, and then the project can be exported to Anypoint Studio, where additional details that bring robustness to the application are implemented by specialized integration developers.

== Build Basic Mule Applications

In spite of being simple, the flow designer is still quite powerful, you can build Mule applications that:

* Send and receive requests via HTTP, FTP, create entries in Data Bases, create files.
* Run tasks at regular intervals.
* Orchestrate processes across APIs, such as Salesforce, Twitter, Facebook, GitHub, Zendesk, and many more.
* Send automatic emails.
* Can powerfully map fields through link:/mule-user-guide/v/4.0/dataweave[DataWeave] transformations to make virtually any two data formats compatible

Just like with link:/anypoint-studio[Anypoint Studio], the resulting application of editing in the flow designer is built for running in a Mule Runtime, either in link:/runtime-manager/deploying-to-cloudhub[CloudHub] or in a link:/runtime-manager/deploying-to-your-own-servers[customer-managed server].

[NOTE]
====
With the flow designer, you currently can't:

* Automatically build out an API backend based on a RAML API definition file _(coming soon)_
* Deploy directly to a customer-managed server (ie: a runtime outside CloudHub) _(coming soon)_
* Write custom code
* Used advanced functionality such as Spring or Maven
* Create Mule projects that run on a runtime version prior to 4.0.0

All of these things can be accomplished with link:/anypoint-studio[Anypoint Studio], our more advanced desktop eclipse-based IDE.
====

== Mule Flows

[TIP]
Refer to link:/mule-user-guide/v/3.8/mule-concepts[Mule Key Concepts] for an overview of basic Mule Runtime concepts.


In the flow designer, the components that compose Mule applications are represented by _cards_. Each component receives an input, carries out a specific function and then passes out an output to the next one. These are chained together into link:/mule-user-guide/v/3.8/mule-concepts#flows[flows].

image:


Every flow has a trigger that sets it into action, this can either be an endpoint component that is externally called, or a poll which actions your flow at a given time or interval. When you create a new Design Center app project, you're immediately prompted to select the component that will trigger your first flow.

image:

You can then build up your flow from there, by adding more components that are executed after the first one is triggered. The order in which they are placed matters, as information flows through them from left to right. To view the metadata that describes this information at every point of the way, see link:/design-center/v/1.0/handling-metadata-in-flow-designer[handling metadata in the flow designer].

image

You add steps to your flow by licking the plus icons that exist in between two existing cards (hover over the arrows in between them to reveal plus icons).

image

You can then pick what component to add to your flow from a list. This list includes all the basic components, as well as APIs taken directly from your organization's link:/mule-fundamentals/v/3.8/anypoint-exchange2[Exchange], exposing content that's created by integration specialists in your organization.

[TIP]
Advanced users can define what assets are made available on the flow designer via Exchange. For example, if you have a custom API for Salesforce and don't want people in your organization to instead use the regular Salesforce connector, you can restrict its use.

You can also create a new flow by clicking the plus sign at the top:

image:

Every flow is triggered and executed independently of each other.

== Card Configuration

You can click on any card to open its settings panel. There, you'll find specific settings that pertain to that element in your flow (if your project includes multiple instances of the same type of card, each is configured separately). Many components also have <<Global Configurations>>, these allow you to set certain parameters globally.

image

Fields can be populated with either a static value, or a reference to another value. Switch between one modality or another by clicking the *expression button*.

image

If the expression mode is enabled, you can either write a link:/mule-user-guide/v/4.0/dataweave[DataWeave] expression, or click the *Map* button to open up an editor window, where you can graphically drag and drop elements from the incoming message and use the full set of features of link:/design-center/v/1.0/using-dataweave-in-flow-designer[DataWeave in flow designer] to build an expression.

image

[TIP]
When using the expression editor, it's implied that whatever you type into the field is a DataWeave expression. Hence, you don't need to wrap your expression in `#[]`.


== Global Configurations

By design, Mule applications keep the reusable configurations of connectors separate from the definition of individual instances of them. This is achieved through link:/mule-user-guide/v/4.0/global-elements[Global Elements], which exist outside any flow, but that can be referenced by elements in them.

image:


In this way, when creating a project that utilizes several instances of a same card, these parameters only need to be provided once and can easily be globally changed.

For example, you could have multiple HTTP connectors in your project, all of them relying on the same host and port and implementing the same SSL certificates, but each triggering a different flow via a different subpath. These would each reference a single global element in the following way:

image


This comes in specially handy when you want to deploy a same project to different environments. When deploying to a different environment, you are prompted to assign a different set of values for these global elements. In this way, you can for example easily point your production deployment to the production database, and your QA deployment to the mock QA database.

image:


== Transform

Through the *Transform* element you can powerfully convert data types and data structures, perform aggregations, filters and much more. See link:/design-center/using-dataweave-in-flow-designer[Using DataWeave in the Flow Designer].

image


== Dealing With Metadata

Each card displays key information about what the component does to the data transitioning through it.

image:

As your data passes through your flows, you can inspect the expected structure of the data at each given point. This data can be of great help in understanding what your application is doing.

See link:/design-center/handling-metadata-in-flow-designer[Handling Metadata in flow designer] for more on this topic.



== Deploy Your Project

You can easily deploy your app straight to CloudHub without leaving the editor. Simply click the *Play* button on the top nav bar. See link:/design-center/deploying-your-project[Deploying Your Project] for more details.

image:

////
[NOTE]
For deploying to customer-managed Mule runtimes (ie: not CloudHub), you must first import your project to Anypoint Studio and export a .zip deployable archive from there.
////


== Debugging

Once you have deployed your project, it's time to test it.

If any of the flows on your project are triggered by a link:/mule-user-guide/v/3.8/poll-reference[Poll] element, then you can trigger that flow manually by clicking on the *Try* button.

image:

If any of the flows on your project are triggered by an HTTP listener connector, you can simply open a browser and hit the path where this is exposed. For example if your project is deployed to myapp.cloudhub.io and your flow is triggered by an HTTP connector that is configured to listen on the subpath `/helloworld`, then you should be able to activate that flow by pointing your browser to `myapp.cloudhub.io/helloworld`.

For sending more advanced HTTP requests that include a body or headers, you can use tools like postman or curl.

=== Viewing Log Data

After your flows have been triggered at least once, and actual data (not just metadata) has gone through them, you can view this data on each of the elements in the flow. The flow designer keeps a record of the messages on each, you can also open an historic view of the messages that came through an element.

image:

[NOTE]
Note that this data is only shown on flow designer when running in development environments. Once you promote your application to a production environment, flow designer can't access data that flows through it.


////
== Export to Studio

If you need to set up more advanced configurations on your Mule project, you can easily export it to link:/anypoint-studio[Anypoint Studio] and open it in this more powerful editor.

To do so, simply click the *Export to Studio* icon on the top nav bar
image:[studio icon]

This generates a full-fledged Mule application, packaged as a .zip file. To learn how to import this file into Anypoint Studio, see link:/anypoint-studio/v/6/importing-and-exporting-in-studio#impoting-projects-into-studio[Importing and Exporting in Studio]

[NOTE]
Make sure you configure Anypoint Studio in your machine to be linked to your Anypoint Platform organization    ...do you have to?
////
