= Handling Metadata
:keywords: mozart


== Data Types


== Custom Data Types

You can define your own data types by:

* Selecting the metadata tab in a connector
* In a Transform card, opening the custom data type editor


== how to populate

how to get to the metadata menu, from transform component and the metadata tab of different elements

what formats supported JSON XML CSV

Sample / schema

=== Custom Data Types

similar to what's in Studio

=== Configure Reader Properties

not confirmed for release....





You can view metadata displayed directly on the different cards. This display says what each card is doing to the Mule message (link)


how to view

data type explorer


what else it's for

* Thanks to the metadata that you make available, the flow designer can also give you intelligent autocomplete suggestions, as well as mapping stuff
* smart suggestions
* DataWeave known inputs and required output structure.  The Map button also opens a DW menu where you can pick from the metadata to populate any field
