= Design Center
:keywords: mozart

The Design Center groups two editors that allow you to easily create tailored connectivity solutions. Both editors are designed to keep you focused on a high-level view of what you're creating, leveraging custom reusable components or leaving backend complexities for a later step.

The Design Center is part of the Anypoint Platform, in order to access this tool you need to own an Anypoint Platform account that has permissions that allow you to create and manage APIs and/or applications.

image:[listed apps]


== API Designer

API Designer lets you create API definition files described in link:raml.org[RAML]. This light-weight YAML-like language lets you specify the API's resources, methods, properties and more, together with samples and schemas.

Once this definition is established, you can import it into Anypoint Studio to automatically create a scaffolding structure upon which you can build out your API's backend, having a clear understanding of the expected inputs and outputs of each operation.

From the RAML definition you can also automatically generate interactive documentation for users of your API, which can be easily exposed on your API's Portal.

== Mozart (beta)

Mozart lets you create fully functional Mule applications, functioning as an on-line simplified alternative to link:/anypoint-studio[Anypoint Studio].

Mozart offers a reduced set of options, tailored to be intuitive and to the point. If you find that you require going deeper into more advanced configuration, you can always export your resulting Mule application into link:/anypoint-studio[Anypoint Studio], the desktop IDE.

== Create New

To create a new project, both for Mozart or API Designer, just click the *Create* button:

image[create]

Then name your project and select the type of your project from the dropdown menu in *Project Type*:

image[project type]

You must also select the link:/access-managemnet/environments[target environment] for your application (ie: Development, QA, Production). Through the use of multiple environments, you can keep your works-in-progress safely away from the public eye until they're ready to be promoted to production.
