= Mozart
:keywords: mozart

Mozart is a simplified web-based visual design tool that allows you to create and deploy Mule applications very easily. It can be though of as a subset of link:/anypoint-studio[Anypoint Studio] that is streamlined to require minimum configuration. With a strong focus on usability, Mozart allows you to get things done with very little effort and without needing to go deep into learning the underlying concepts. It's oriented towards users that, whilst having a general technical background, don't need to understand Java or advanced connectivity concepts.

The Mozart editor allows you to directly deploy your applications to CloudHub without ever leaving the screen. Applications built in Mozart can also be exported to Anypoint Studio for configuring advanced settings.

Mozart also allows you to build upon reusable assets, enabling ad hoc integrators to compose their applications in a self-serve manner by combining general use assets that have been created by integration specialists.


You can have a workflow where you periodically deploy your project to a Dev environment while building and debugging, and then – when ready – you can simply change the deployment target to the Production environment, all without ever leaving the editor. Alternatively, you could have a workflow where the desired overall functionality is drafted by line-of-business users on Mozart, and then the project is exported to Anypoint Studio, where additional details that bring robustness to the application are implemented by specialized integration developers.

== Build Basic Mule Applications

In spite of being simple, Mozart is still quite powerful, you can build Mule applications that:

* Send and receive requests via HTTP, FTP, create entries in Data Bases, create files.
* Run tasks at regular intervals.
* Orchestrate processes across APIs, such as Salesforce, Twitter, Facebook, GitHub, Zendesk, and many more.
* Send automatic emails.
* Can powerfully map fields through link:/mule-user-guide/v/4.0/dataweave[DataWeave] to make virtually any two data formats compatible

Just like applications created through link:/anypoint-studio[Anypoint Studio], the resulting application of editing in Mozart is built for running in a Mule Runtime, either in CloudHub or in an on-premises server.

[NOTE]
====
With Mozart, you currently can't:

* Automatically build out an API backend based on a RAML API definition file _(coming soon)_
* Deploy directly to a customer-owed server (ie: any server on-premises) _(coming soon)_
* Write custom code
* Used advanced functionality such as Spring or Maven
* Create Mule projects that run on a runtime version prior to 4.0.0

All of these things can be accomplished with link:/anypoint-studio[Anypoint Studio], our more advanced eclipse-based IDE.
====

== Mule Flows

[TIP]
Refer to link:/mule-user-guide/v/3.8/mule-concepts[Mule Key Concepts] for an overview of basic Mule Runtime concepts.


In Mozart, the building blocks of Mule applications are called cards. Each card receives an input, carries out its function and then passes out an output to the next card. These are arranged into link:/mule-user-guide/v/3.8/mule-concepts#flows[flows], that determine the order in which each is executed.

image:


Every flow has a trigger that sets it into action, this can either be an endpoint card that is externally called, or a poll which actions your flow at a given time or interval.

When you create a new Mozart project, you're immediately prompted to select the triggering card of the first flow.

image:

You can then build up your flow from there, by adding more cards that are executed after the first one is triggered. The order in which they are placed matters, as information flows through them from left to right. To view the metadata that describes this information at every point of the way, see link:/design-center/v/1.0/handling-metadata-in-mozart[handling metadata in Mozart].

image

You add steps to your flow by licking the plus icons that exist in between two existing cards (hover over the arrows in between them to reveal plus icons).

image

You can then pick what element to add to your flow from a list. This list includes all the basic connectors and components, as well as APIs taken directly from your organization's link:/mule-fundamentals/v/3.8/anypoint-exchange2[Exchange], exposing content that's created by integration specialists in your organization, making it self-serve for anyone who needs to put together an integration.

[TIP]
Advanced users can define what assets are made available on Mozart via Exchange. For example, if you have a custom API for Salesforce and don't want people in your organization to use it through the regular Salesforce connector, you can restrict its use.

You can also create a new flow by clicking the plus sign at the top:

image

Every flow is triggered and executed independently of each other.




== Global Configurations

By design, Mule applications keep the reusable configurations of connector cards separate from the definition of individual instances of them. This is achieved through link:/mule-user-guide/v/4.0/global-elements[Global Elements], which live outside Mule flows, but that can be referenced by elements in them.

image


In this way, when creating a project that utilizes several instances of a same card, these parameters only need to be provided once and can easily be globally changed. This also allows you to deploy a same project to different environments, as you can assign a different set of values for these global elements for every environment.

image:


For example, you could have multiple HTTP connectors in your project, all of them relying on the same host and port and implementing the same SSL certificates, but each triggering a different flow via a different subpath. These would each reference a single global element in the following way:

image



== View Metadata

Each card displays key information about what it does to your metada



As your data passes through your flows, you can inspect the expected structure of the data at each given point. This data can be of great help in understanding what your application is doing.

See link:/design-center/handling-metadata-in-mozart[Handling Metadata in Mozart] for more on this topic.

image


== Transform

Through the *Transform* element you can powerfully convert data types and data structures, perform aggregations, filters and much more. See link:/design-center/using-dataweave-in-mozart[Using DataWeave in Mozart].

image

== Deploy Your Project

You can easily deploy your app straight to CloudHub without leaving the editor. Simply click the *Play* button on the top nav bar. See link:/design-center/deploying-your-project[Deploying Your Project] for more details.

image

[NOTE]
For deploying to customer-managed Mule runtimes (ie: not CloudHub), you must first import your project to Anypoint Studio and export a .zip deployable archive from there.


== Export to Studio

If you need to set up more advanced configurations on your Mule project, you can easily export it to link:/anypoint-studio[Anypoint Studio] and open it in this more powerful editor.

To do so, simply click the *Export to Studio* icon on the top nav bar
image:[studio icon]

This generates a full-fledged Mule application, packaged as a .zip file. To learn how to import this file into Anypoint Studio, see link:/anypoint-studio/v/6/importing-and-exporting-in-studio#impoting-projects-into-studio[Importing and Exporting in Studio]

[NOTE]
Make sure you configure Anypoint Studio in your machine to be linked to your Anypoint Platform organization    ...do you have to?
