= Mozart
:keywords: mozart

Mozart is a simplified online editor that allows you to create and deploy integration applications very easily. It can be though of as a subset of link:/anypoint-studio[Anypoint Studio] that requires minimum configuration.

With a strong focus on usability, Mozart allows you to get things done with very little effort and without needing to go deep into any of the underlying concepts. It's oriented towards users that, whilst having a general technical background, don't need to understand Java or advanced connectivity concepts.

Applications built in Mozart can be directly deployed to CloudHub without needing to leave the editor window.

Applications built in Mozart can also imported into Anypoint Studio for configuring advanced settings. You could set up a workflow where the desired overall functionality is drafted by line-of-business users in Mozart, and then additional details for more robustness are implemented by more technical developers in Anypoint Studio.

== Build Basic Mule Applications

In spite of being simple, Mozart is still quite powerful, you can build Mule applications that:

* Send and receive requests via HTTP, FTP, create entries in Data Bases, create file.
* Connect to Salesforce, Twitter, Facebook, GitHub, Zendesk, etc.
* Run at regular intervals.
* Send automatic emails.
* Can powerfully map fields through link:/mule-user-guide/v/4.0/dataweave[DataWeave]

[TIP]
Refer to link:/mule-user-guide/v/3.8/mule-concepts[Mule Key Concepts] for an overview of basic Mule Runtime concepts.



Just like applications created through link:/anypoint-studio[Anypoint Studio], the resulting application of editing in Mozart is built for running in a Mule Runtime, either in CloudHub or in an on-premises server.

[NOTE]
For deploying to customer-managed Mule runtimes (all except CloudHub), you must first import your project to Anypoint Studio and export a .zip deployable archive from there.

== Creating Flows

Mule applications are based on components that are arranged into link:/mule-user-guide/v/3.8/mule-concepts#flows[flows]. When you create a new Mule project, a first flow is implicitly already created.

Every flow has a trigger that sets it into action, this can either be

== Global Configurations



== Mappings


== Export to Studio

link to studio

== Deploy to Runtime Manager

link to RM
