= HTTP Connectors
:keywords: anypoint studio, esb, connectors, http, https, http headers, query parameters, rest, raml
:toc:
:toc-title:



toc::[]


HTTP connectors are accessible from your Mule application design palette, typing "HTTP" in the search bar.

* The HTTP listener and requester require a *connector configuration*.
* Build HTTP requests and responses using the `#[attributes]`.
* For HTTPS, select that protocol and set up a *TLS Context*.
* Authenticate incoming requests using the Basic Auth Security Filter after a HTTP listener.

=== HTTP Listener

link:/core-connectors/v/latest/http-listener-reference[HTTP Listener]

Use the HTTP listener in the source (left) side of a flow to listen for requests that should trigger a Mule flow.

* Listen for the desired HTTP request(s)
* Build a response for the HTTP client that sent the request, processing it through the flow as necessary.

// List special configuration procedures from above doc below

=== HTTP Requester

Use to send requests to a certain address. Receive and process the returned response. Place the HTTP requester in the process (right) side of the flow.

The request will return a `MuleMessage` with specific `HttpResponseAttributes`.

* See how to map HTTP Requests to Mule Message in the link:/core-connectors/v/latest/http-requester[HTTP Requester] doc.

=== Load Static HTTP Resource

Add the Load Static Resource operation to return to a requester a static HTTP resource, such as .html, CSS, scripts, etc. This gets sent back automatically with the response.

Put the Load Static Resource component in the flow and define the resource to send, or a default resource in case of failure.

link:/load-static-resource[Load Static Resource]

=== Basic Auth Security Filter

Put a listener and then security filter to secure and authenticate requests to your service.

link:/basic-auth-security-filter[Load Static Resource]


== Additional Reference

Other attributes in this connector allow you to set up more advanced functionality such as response timeout, set whether redirects are followed, cookies gathered from responses and if responses are parsed.

=== Send or Receive HTTPS requests

[NOTE]
Configuration depends on whether you have a HTTP server or client and whether or not you need two-way authentication.

Set the protocol to HTTPS in the configuration. Configure a TLS Context (keystore and/or trust store). See
link:/mule-user-guide/v/3.8/tls-configuration[TLS Configuration]. Setting both a trust store and a key store means you are setting up two-way TLS.

*One-way scenarios*

- Server implements *key store* to enforce client authentication
- Client implements *trust store* (JVM's will be used if not provided)

=== Migrate from Mule 3 HTTP Connectors

The migration paths are different depending on the version of Mule you were using before.

In Mule 4, you reference HTTP parameters from the attributes object if using the connectors. Do this using DataWeave syntax using the reference table provided in the listener and requester documentation.
//TODO

=== Map HTTP Responses to Mule Messages

An HTTP response is mapped to the Mule message in exactly the same way that the HTTP request is mapped to a Mule message in the HTTP Listener Connector, except that the following elements don’t apply to HTTP responses:

* Query parameters
* URI parameters
* All inbound properties related to the HTTP request URI

In addition, the HTTP Request Connector adds the following inbound properties to the Mule message when receiving a response:

`http.status`: Status code of the HTTP response
`http.reason`: Reason phrase of the HTTP response



== See Also

* See the link:/mule-user-guide/v/3.8/http-connector-reference[full reference]﻿ for the available XML configurable options in this connector.
